name: CI

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install
      run: yarn install
    
    - name: Build
      run: yarn build

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint



  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Coverage
        run: yarn test:cov

  publish:
    needs: [build, tests, coverage]
    if: (github.ref == 'refs/heads/main') && needs.tests.result == 'success' && needs.coverage.result == 'success'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'

      - name: Install
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Discover Version
        id: determine_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          bump_each_commit: true
          short_tags: false
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          format: "${major}.${minor}.${patch}"
     
      - name: Set Version
        run: yarn version --no-git-tag-version --no-commit-hooks --new-version ${{ steps.determine_version.outputs.version }}

      - name: Publish
        run: yarn publish
